### PR TITLE
Added RabinKarp Algorithm

### PR DESCRIPTION
**Pull request by aakashraj01**

### CODE REVIEW

**Comment by adielliot37** [comment]
star fork and follow for pr to get accepted immediately

**Comment by aakashraj01** [comment]
@adielliot37 Done..can you know merge this :)

**Comment by adielliot37** [comment]
> @adielliot37 Done..can you know merge this :)

okay done
please do follow me also

**Comment by aakashraj01** [comment]
Sure..I am following...Also can you add @adielliot37 hacktoberfest 2022 accepted label on this 
so that it can count my pr merge

**Comment by adielliot37** [comment]
I think it is already added as previous pr got accepted in hacktober

**Pull request merged**
